cleanup

diff --git a/scripts/openstack-quickstart-demosetup b/scripts/openstack-quickstart-demosetup
--- a/scripts/openstack-quickstart-demosetup
+++ b/scripts/openstack-quickstart-demosetup
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 
 # go in a directory everybody can access
 # (postgresql commands usually have a 'could not change to "$PWD"' error
@@ -395,13 +395,13 @@ fi
 ### wait until neutron will start
 cnt=0
 while : ; do
-	if [[ $cnt -gt 6 ]] ; then
-		echo "Can't reach neutron server. Exiting !!!" >&2
-		exit 1
-	fi
-        neutron net-list && break
-	cnt=$(($cnt+1))
-        sleep 2
+    if [[ $cnt -gt 6 ]] ; then
+        echo "Can't reach neutron server. Exiting !!!" >&2
+        exit 1
+    fi
+    neutron net-list && break
+    cnt=$(($cnt+1))
+    sleep 2
 done
 ### create subnets
 ## fixed
