Create manila-shares volume group
Reuse existing code for cinder VG and also create
a VG for Manila to be able to use Manila's LVM driver for testing.

diff --git a/scripts/openstack-loopback-lvm b/scripts/openstack-loopback-lvm
--- a/scripts/openstack-loopback-lvm
+++ b/scripts/openstack-loopback-lvm
@@ -1,36 +1,59 @@
 #!/bin/sh
 
+function truncate_file()
+{
+    local f=$1
+    # calc wanted size
+    size=$(df -P -k $(dirname $f)|tail -1| \
+                  perl -ne 'm/^\S+\s*\d+\s+\d+\s+(\d+)/; print int($1*0.3)')
+
+    if [ $size -le 2000000 ] ; then
+        echo "error detecting free space or FS too small: $size KB"
+        exit 12
+    fi
+    truncate --size=${size}K $f
+}
+
+function setup_vg()
+{
+    local vg_name=$1
+    local loop_dev=$2
+    local loop_file=$3
+
+    vgchange -an $vg_name
+    if ! test -e $loop_file ; then
+        truncate_file $loop_file
+    fi
+
+    losetup $loop_dev $loop_file
+    pvcreate $loop_dev
+    vgcreate $vg_name $loop_dev
+    vgchange -ay $vg_name
+
+}
+
+####################
+# script starts here
+####################
 systemctl enable lvm2-lvmetad
 systemctl start lvm2-lvmetad
 
-f=/var/lib/cinder/volumes-pv
-loop=/dev/loop0
 modprobe loop
 
+# enable or create cinder-volumes VG
 if vgs |grep -q cinder-volumes ; then
   echo "using existing cinder-volumes VG"
   vgchange -ay cinder-volumes
-  exit 0
+else
+    # create new VG
+    setup_vg "cinder-volumes" "/dev/loop0" "/var/lib/cinder/volumes-pv"
 fi
 
-# stop/cleanup
-#vgremove cinder-volumes
-vgchange -an cinder-volumes
-#losetup -d $loop
-
-if ! test -e $f ; then
-	# calc wanted size
-	size=$(df -P -k /var/lib/cinder/|tail -1| perl -ne 'm/^\S+\s*\d+\s+\d+\s+(\d+)/; print int($1*0.3)')
-
-	if [ $size -le 2000000 ] ; then
-		echo "error detecting free space or FS too small: $size KB"
-		exit 12
-	fi
-
-	truncate --size=${size}K $f
+# enable or create manila-shares VG
+if vgs |grep -q manila-shares ; then
+  echo "using existing manila-shares VG"
+  vgchange -ay manila-shares
+else
+    # create new VG
+    setup_vg "manila-shares" "/dev/loop1" "/var/lib/manila/shares-pv"
 fi
-losetup $loop $f
-pvcreate $loop
-vgcreate cinder-volumes $loop
-
-vgchange -ay cinder-volumes
